# Generated by Django 2.2.3 on 2021-03-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(verbose_name='Номер версии')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование портала')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='osk_update_projects.Version', verbose_name='Номер версии')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256, verbose_name='Изменения')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='osk_update_projects.Version', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Изменения',
                'verbose_name_plural': 'Изменения',
                'ordering': ['id'],
            },
        ),
    ]
